#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

VENV_PATH_BASE=/opt/chameleon
VENV_DIR=.cclogin-venv
VENV_PATH="${VENV_PATH_BASE}/${VENV_DIR}"

mkdir -p /opt/chameleon

python3 -m venv $VENV_PATH

# Install ccauth package which provides cc-login command
$VENV_PATH/bin/pip install --upgrade \
    pip \
    wheel
$VENV_PATH/bin/pip install git+https://github.com/ChameleonCloud/ccauth.git

# Add the cc-login command to PATH
ln -sf $VENV_PATH/bin/cc-login /usr/local/bin/cc-login
