#!/bin/bash

export RCLONE_V="v1.69.1"
export RCLONE_URL_BASE="https://github.com/rclone/rclone/releases/download/${RCLONE_V}"
export RCLONE_AMD_DEB_URL="${RCLONE_URL_BASE}/rclone-${RCLONE_V}-linux-amd64.deb"
export RCLONE_ARM_DEB_URL="${RCLONE_URL_BASE}/rclone-${RCLONE_V}-linux-arm.deb"
export RCLONE_AMD_RPM_URL="${RCLONE_URL_BASE}/rclone-${RCLONE_V}-linux-amd64.rpm"
