#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
  set -x
fi
set -eu
set -x
set -o pipefail

release="rhel${DIB_RELEASE%-*}"

# Add Nvidia's RHEL repo, which contains driver and CUDA packages
${YUM} \
  config-manager -y \
  --add-repo \
  "https://developer.download.nvidia.com/compute/cuda/repos/${release}/$(uname -m)/cuda-${release}.repo"
