#!/bin/bash

# see https://github.com/openstack/diskimage-builder/tree/master/diskimage_builder/elements/bootloader


# DIB_GRUB_TIMEOUT sets the grub menu timeout. It defaults to 5 seconds. Set this to 0 (no timeout) for fast boot times.
export DIB_GRUB_TIMEOUT=0

# Defaults, override if needed
# export DIB_BOOTLOADER_USE_SERIAL_CONSOLE='True'
# export DIB_BOOTLOADER_VIRTUAL_TERMINAL='tty0'

# ttys0 is only default for amd64, leave unset so arm64 overrides it
# export DIB_BOOTLOADER_SERIAL_CONSOLE='ttyS0,115200'

# Defaults to True, but only matters for VMs with some flaky hypervisors.
# Leaving it out unless we observe issues, can roll back
export DIB_NO_TIMER_CHECK='False'

# DIB_BOOTLOADER_DEFAULT_CMDLINE sets parameters that are appended to the 
# GRUB_CMDLINE_LINUX_DEFAULT values in grub.cfg configuration. 
# defaults to nofb nomodeset gfxpayload=text.
# - nofb: removed, appears to be a no-op for ~20 years??
# - nomodeset: removed, causes all sorts of issues with amdgpu, 
#              and can cause excessive on some baremetal servers!
# - gfxpayload=text: kept; probably ok, tells grub not to leave it at `auto`, 
#                    and only impacts what video drivers load
# - pci=realloc=off: added needed to handle badness on ubuntu with ubuntu and multi-gpus
#                    centos distros have it turned off already
export DIB_BOOTLOADER_DEFAULT_CMDLINE="gfxpayload=text pci=realloc=off"
