#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# The default python version for CentOS 8 is python3.6, which is EOL
# A more up-to-date python is required to install our openstack clients
update-alternatives --set python3 "$(which python3.9)"
