#!/bin/bash

# dib-lint: disable=sete setu setpipefail dibdebugtrace

cat << EOF

GETTING HELP

    If you need help, please contact the Chameleon Help Desk at:
    https://www.chameleoncloud.org/user/help/
EOF
