#!/bin/bash

cat << EOF

FIREWALL STATUS

    You can run the following command to check the status of the firewall:
    systemctl is-active firewalld

    Bare metal instances use firewalld to manage the firewall:
    https://chameleoncloud.readthedocs.io/en/latest/technical/networks/networks_basic.html#firewall

    Instances on KVM should have firewalld disabled and use security groups instead:
    https://chameleoncloud.readthedocs.io/en/latest/technical/networks/networks_basic.html#security-groups
EOF
