#!/bin/bash

REGION=$(cc-read-vendordata "region")
if [ "${REGION}" = "KVM@TACC" ]; then
  exit 0
fi

NODE_ID=$(cc-read-vendordata "node")
SITE=$(cc-read-vendordata "site")
CLUSTER=$(cc-read-vendordata "cluster")

cat << EOF

NODE INFORMATION

    Find hardware information about this node by running the following command:
    source ~/openrc
    openstack reservation host show ${NODE_ID}

EOF
