#!/bin/bash

# dib-lint: disable=sete setu setpipefail dibdebugtrace

REGION=$(jq -r '.chameleon.region // empty' "/var/cache/vendordata2.json")
if [ "${REGION}" = "KVM@TACC" ]; then
    if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
        exit 0
    else
        return 0
    fi
fi

NODE_ID=$(jq -r '.chameleon.node // empty' "/var/cache/vendordata2.json")

echo -e "\nNODE INFORMATION"

if [ -z "$NODE_ID" ]; then
    echo -e "\n    Node information is not available."
    if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
        exit 0
    else
        return 0
    fi
fi

cat << EOF

    Discover information about this node:

    source ~/openrc
    openstack reservation host show ${NODE_ID}
EOF
