#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

script_path=/usr/local/sbin/dhcp-all-interfaces.sh

cat /tmp/in_target.d/dhcp-all-interfaces.sh > "${script_path}"
sed -i "s/DIB_DHCP_TIMEOUT/${DIB_DHCP_TIMEOUT:-30}/" "${script_path}"
