#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

case "$DISTRO_NAME" in
    "centos")
        systemctl enable chronyd.service
        ;;
    "ubuntu")
        systemctl enable chrony.service
        ;;
esac
