#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

ln -sf /etc/systemd/system/cache-vendordata.timer \
    /etc/systemd/system/timers.target.wants/cache-vendordata.timer
