#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# ubuntu adds these automatically, we don't want them
rm -f /etc/update-motd.d/10-help-text
rm -f /etc/update-motd.d/50-landscape-sysinfo
rm -f /etc/update-motd.d/50-motd-news
rm -f /etc/update-motd.d/90-updates-available
rm -f /etc/update-motd.d/91-contract-ua-esm-status
rm -f /etc/update-motd.d/91-release-upgrade
rm -f /etc/update-motd.d/92-unattended-upgrades
rm -f /etc/update-motd.d/95-hwe-eol

# add our custom messages
cp /etc/custom-motd/* /etc/update-motd.d/
