#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

upstream_version="${DIB_RELEASE//-stream/}"

# Package repository for puppetserver
${YUM} install -y "https://yum.puppet.com/puppet-release-el-${upstream_version}.noarch.rpm"

# Extra Packages for Enterprise Linux repository
${YUM} install -y "https://dl.fedoraproject.org/pub/epel/epel-release-latest-${upstream_version}.noarch.rpm"
if [[ "${upstream_version}" -ge 9 ]]; then
  powertools_repo=crb
else
  powertools_repo=powertools
fi

if [[ "${upstream_version}" -ge 8 ]]; then
  ${YUM} config-manager --set-enabled "${powertools_repo}"
fi
