#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -x
set -o pipefail

# Load Nvidia's apt keys
nvidia_release="${DIB_DISTRO_VERSION//\./}"
case "${ARCH}" in
    amd64) platform=x86_64 ;;
    arm64) platform=sbsa ;;
    *)
        echo "Unsupported architecture: ${ARCH}" >&2
        exit 1
        ;;
esac
keyring_pkg_url=https://developer.download.nvidia.com/compute/cuda/repos/ubuntu"$nvidia_release"/"$platform"/"${DIB_NVIDIA_KEYRING_PKG}"
cached_pkg="${DIB_IMAGE_CACHE}/cuda/${platform}-${DIB_NVIDIA_KEYRING_PKG}"
if [[ ! -f "${cached_pkg}" ]]; then
    echo "Nvidia keyring package not cached. Downloading a new copy..."
    wget --show-progress -O "${cached_pkg}" "${keyring_pkg_url}"
fi

cp "${cached_pkg}" "${TMP_HOOKS_PATH}/${DIB_NVIDIA_KEYRING_PKG}"
