#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# install cloudfuse
git clone https://github.com/ChameleonCloud/cc-cloudfuse.git
cd cc-cloudfuse/
./configure
make
echo "Testing cloudfuse binary..."
test_code=1
./cloudfuse || test_code=$?
# We expect code 1 because authentication will fail.
# Other codes usually indicate a fatal signal was sent
if  [[ 1 != "${test_code}" ]]; then
  echo "Issue building cloudfuse binary!"
  exit ${test_code}
fi
make install

# clean up
cd ..
rm -rf cc-cloudfuse

exit 0
