#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -x
set -o pipefail

mkdir -p /etc/apt/keyrings/
cp /tmp/in_target.d/keyrings/*.gpg /etc/apt/keyrings/

echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/6.3.3 noble main" > /etc/apt/sources.list.d/rocm.list
#echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/amdgpu.gpg] https://repo.radeon.com/amdgpu/6.3.3/ubuntu noble main" > /etc/apt/sources.list.d/amdgpu.list

apt-get update -y
