#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
  set -x
fi
set -eu
set -o pipefail

if [[ $(update-alternatives --display ip6tables) ]] 2>&1> /dev/null; then
  # https://github.com/husarnet/docker-example/issues/1
  update-alternatives --set ip6tables /usr/sbin/ip6tables-nft
else
  update-alternatives --install /usr/bin/ip6tables ip6tables /usr/sbin/ip6tables-nft 100
fi
