#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Delete existing rules
bash -c "yes || true" | ufw reset

# Establish firewall rules
ufw allow ssh
ufw allow from 10.0.0.0/8
ufw allow from 172.16.0.0/12
ufw allow from 192.168.0.0/16
ufw default deny incoming || true

# Enable ufw
# UFW can't run inside the chroot during image build, causing errors if we enable it here
# ufw --force enable

# Instead, create a rc.local file, this will be executed by systemd rc-local.service on boot
cat > /etc/rc.local <<- 'EOM'
#!/bin/sh
ufw --force enable
EOM
# Ensure that /etc/rc.local is executable
chmod +x /etc/rc.local
