#!/bin/bash

# Writes a base64-encoded JSON (to avoid escape issues) stored in an env
# var "DIB_CC_PROVENANCE" to a file stored in the image output directory.

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

DIB_CC_PROVENANCE=${DIB_CC_PROVENANCE:-e30K} # e30K = '{}\n'

mkdir -p ${DIB_MANIFEST_SAVE_DIR} # this comes from our dependency on manifests
CC_IMAGE_BASE_NAME="$(basename ${IMAGE_NAME})"
echo "${DIB_CC_PROVENANCE}" | base64 -d | python3 -mjson.tool > "${DIB_MANIFEST_SAVE_DIR}/${CC_IMAGE_BASE_NAME}_provenance.json"
