#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

SCRIPTDIR=$(dirname "$0")

python3 -m pip install --upgrade pip
python3 -m pip install --ignore-installed -r "${SCRIPTDIR}/../requirements.txt"
