#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
  set -x
fi
set -eu
set -o pipefail

QUARTUS_RUNFILE_NAME="QuartusProProgrammerSetup-${DIB_QUARTUS_VERSION}-linux.run"
QUARTUS_LOCAL_FILE="${DIB_IMAGE_CACHE}/fpga/${QUARTUS_RUNFILE_NAME}"

if [[ ! -f "${QUARTUS_LOCAL_FILE}" ]]; then
  wget --show-progress -O "${QUARTUS_LOCAL_FILE}" "${DIB_QUARTUS_RUNFILE_URL}"
fi

cp "${QUARTUS_LOCAL_FILE}" "${TMP_HOOKS_PATH}"
