#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
  set -x
fi
set -eu
set -x
set -o pipefail

upstream_version="${DIB_RELEASE//-stream/}"

cuda_distro="rhel${upstream_version}"
cuda_arch=$(uname -m)

${YUM} \
  config-manager -y \
  --add-repo \
  "https://developer.download.nvidia.com/compute/cuda/repos/$cuda_distro/$cuda_arch/cuda-$cuda_distro.repo"
