#!/bin/bash

cuda_config_path="/etc/profile.d/cuda-config.sh"

cat > "${cuda_config_path}" <<- 'EOM'
export PATH=/usr/local/cuda/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

EOM

chmod +x "${cuda_config_path}"
